# https://espanso.org/docs/
matches:
  # Obsidian Triggers
  - trigger: "/today"
    replace: "[[{{today}}]]"
    vars:
      - name: today
        type: date
        params:
          format: "%B %e, %Y"

  - trigger: "/yesterday"
    replace: "[[{{output}}]]"
    vars:
      - name: output
        type: shell
        params:
          cmd: "date --date=\"yesterday\" +\"%B, %e, %Y\""
          format: "%B %e, %Y"

  - trigger: "/tomorrow"
    replace: "[[{{output}}]]"
    vars:
      - name: output
        type: shell
        params:
          cmd: "date --date=\"next day\" +\"%B, %e, %Y\""
          format: "%B %e, %Y"
